version: '3'

services:
  postgres:
    container_name: postgres-db
    image: postgres:9.6.6
    ports: 
      - 5432:5432
    volumes:
      - ./pgdb:/var/lib/postgresql/data
    restart: always
    env_file: .env_docker
    environment:
      - LC_ALL=C.UTF-8

  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: "always"
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/vhost/:/etc/nginx/vhost.d:ro
      - ./nginx/conf.d/client_max_body_size.conf:/etc/nginx/conf.d/client_max_body_size.conf:ro
      - ./static/:/code/static/
      - ./media/:/code/media/

  web:
    build: .
    restart: "always"
    ports:
      - "8000:8000"
    volumes:
      - .:/code/
      - ./static/:/code/static/
      - ./media/:/code/media/
    environment:
      - VIRTUAL_HOST=localhost, 35.225.243.133
      - VIRTUAL_PORT=8000
      - DEBUG=False
    depends_on:
      - "postgres"
