# Generated by Django 3.0 on 2020-03-26 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('magapp', '0002_auto_20200326_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='user_comment_impressions',
            field=models.ManyToManyField(related_name='user_comment_impressions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='comments',
            name='usercomment',
        ),
        migrations.AddField(
            model_name='comments',
            name='usercomment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
