# Generated by Django 3.0 on 2020-03-28 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magapp', '0005_auto_20200326_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='magapp.Article'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='short_description',
            field=models.TextField(verbose_name='Short_Description'),
        ),
    ]
