# Generated by Django 3.0 on 2020-03-29 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('magapp', '0008_auto_20200328_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commentsclone',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentsclone', to='magapp.Article'),
        ),
        migrations.AlterField(
            model_name='commentsclone',
            name='comment_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentsclone', to=settings.AUTH_USER_MODEL),
        ),
    ]
