# Generated by Django 3.0 on 2020-03-30 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magapp', '0009_auto_20200329_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='article',
        ),
    ]
