# Generated by Django 3.0 on 2020-04-11 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('magapp', '0010_remove_comments_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.TextField(verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='user_comment_impressions',
            field=models.ManyToManyField(blank=True, related_name='user_comment_impressions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commentsclone',
            name='comment',
            field=models.TextField(verbose_name='Comments'),
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'mesaj',
                'verbose_name_plural': 'mesajlar',
                'ordering': ('message',),
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100, verbose_name='Group-name')),
                ('group_user', models.ManyToManyField(related_name='group', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'qrup',
                'verbose_name_plural': 'qruplar',
                'ordering': ('group_name',),
            },
        ),
    ]
