# Generated by Django 3.0 on 2020-04-16 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magapp', '0013_chatmessage_thread'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='first',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='second',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='Thread',
        ),
    ]
